## Word Embedding Techniques using Embedding Layer in Keras

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### Vocabulary size
voc_size=10000

In [5]:
one_set=[one_hot(words,voc_size)for words in sent]

In [6]:
one_set

[[9545, 9386, 5288, 5541],
 [9545, 9386, 5288, 9144],
 [9545, 4874, 5288, 616],
 [9957, 8033, 8079, 4476, 1623],
 [9957, 8033, 8079, 4476, 2744],
 [9439, 9545, 3167, 5288, 3018],
 [6530, 269, 6135, 4476]]

In [7]:
max_length = 0  # Rename the variable to avoid conflict with the len function
for i in sent:
    x = len(i)
    print(x)

17
18
14
15
21
31
20


## Word Embedding Represntation

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_set,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9545 9386 5288 5541]
 [   0    0    0    0 9545 9386 5288 9144]
 [   0    0    0    0 9545 4874 5288  616]
 [   0    0    0 9957 8033 8079 4476 1623]
 [   0    0    0 9957 8033 8079 4476 2744]
 [   0    0    0 9439 9545 3167 5288 3018]
 [   0    0    0    0 6530  269 6135 4476]]


In [11]:
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [14]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 170ms/step
[[[-5.54063171e-03 -2.49963757e-02  7.09403679e-03  1.97517015e-02
   -4.46389802e-02 -3.83460410e-02  3.41210999e-02  2.36220695e-02
    1.54283904e-02 -1.86058171e-02]
  [-5.54063171e-03 -2.49963757e-02  7.09403679e-03  1.97517015e-02
   -4.46389802e-02 -3.83460410e-02  3.41210999e-02  2.36220695e-02
    1.54283904e-02 -1.86058171e-02]
  [-5.54063171e-03 -2.49963757e-02  7.09403679e-03  1.97517015e-02
   -4.46389802e-02 -3.83460410e-02  3.41210999e-02  2.36220695e-02
    1.54283904e-02 -1.86058171e-02]
  [-5.54063171e-03 -2.49963757e-02  7.09403679e-03  1.97517015e-02
   -4.46389802e-02 -3.83460410e-02  3.41210999e-02  2.36220695e-02
    1.54283904e-02 -1.86058171e-02]
  [ 4.47858237e-02 -4.11745161e-03  2.95283310e-02  1.89648159e-02
    2.93897279e-02 -1.88115984e-03 -9.26874951e-03  1.19472146e-02
   -1.49158612e-02 -3.92840393e-02]
  [-7.04177469e-03 -3.17254066e-02  3.44969891e-02 -2.70381812e-02
    3.33573557e-02 -4.28737178